name: Email Verification Action

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 22f3003001@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
      - name: Display completion message
        run: echo "Action completed successfully!"
